name: cowsay artwork

on: push

jobs:
    cowsay_job:
        runs-on: ubuntu-latest
        steps:
        -   name: Checkout Repo
            uses: actions/checkout@v4

        -   name: list of all file
            run: ls -ltra

        -   name: Excute script
            run: |
                chmod +x cowsay.sh
                ./cowsay.sh